### ISSUE TITLE
gcc_5.3 is not gcc 5.3

### ISSUE THREAD

**Issue by nathanaeljones** [lasote/conan-docker-tools#1]
Xenial now uses gcc 5.4 by default, so rebuilding these Dockerfiles causes gcc_5.3 to include gcc 5.4.

**Comment by lasote** [comment]
Thanks for notice it. Do you know a way to downgrade to 5.3?

**Comment by nathanaeljones** [comment]
No, I don't. I just upgraded to 5.4 since it's supposed to be backwards compatible etc.  I'm focusing on 5.4, 4.8, and 4.9. 

I spent most of today refactoring the dockerfiles; I now have very compact images: https://github.com/imazen/imageflow/tree/master/ci

**Comment by nathanaeljones** [comment]
I also can't link against littlecms under gcc 5.4 ...  :(

https://travis-ci.org/imazen/imageflow/builds/153485008

At this point I'm almost ready to make some sanity check for -fPIC to verify symbols are right at dependency build time.....

**Comment by lasote** [comment]
I'm pushing a new lasote/conangcc53 and reuse the old 5.3 to 5.4.
I'll look to littlecms. Closing this issue. Thanks!
