### ISSUE TITLE
Docker image for clang-3.9

### ISSUE THREAD

**Issue by uilianries** [lasote/conan-docker-tools#4]
**What?**  
Develop a new docker image based on Ubuntu 17.04 + clang-3.9

**Why?**  
Conan project support many compilers, including clang on Linux.

**How?**  
Provide lasote/conanclang39 image by hub.docker

**Comment by Croydon** [comment]
@lasote Would you accept pull requests for that?

**Comment by Croydon** [comment]
According to https://github.com/conan-io/conan-package-tools/issues/13 I think the answer is yes.
